### ISSUE TITLE
Deploy assumes there is an SSH endpoint to connect to

### ISSUE THREAD

**Issue by teelahti** [rgardler/acs-scripts#12]
When running python `acs.py deploy -c myconfig.ini` for the first time the operation fails on 

> Traceback (most recent call last):
  File "acs.py", line 66, in <module>
    main()
  File "acs.py", line 27, in main
    acs = ACSUtils(options.config_file)
  File "/Users/tero/repositories/timesiege/deployment/cloud/acs-scripts/acs/acs_utils.py", line 31, in __init__
    self.ssh.connect(self.getManagementEndpoint(), username = self.config.get('ACS', "username"), port=2200)
  File "/Library/Python/2.7/site-packages/paramiko/client.py", line 283, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/Library/Python/2.7/site-packages/paramiko/client.py", line 187, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known 

This is most probably due to the fact that acs_utils.py has __init__ that tries to open an SSH tunnel to an endpoint that does not (yet) exist:

    self.ssh = SSHClient()
    self.ssh.load_system_host_keys()
    self.ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    self.ssh.connect(self.getManagementEndpoint(), username = self.config.get('ACS', "username"), port=2200)
    self._configureSSH()

Reading the deployment commands, it clearly is intended to create everything from scratch including the resource group and all management endpoints. Therefore I think this is a bug in the script.

**Comment by rgardler** [comment]
Thanks for the patch :-)
